validate:
    type_names: PascalCase
    field_names: camelCase
    enum_values: PascalCase
transform:
    type_names: PascalCase
    field_names: camelCase
    enum_values: uppercase
    drop_comments: true
generation:
    add_query_type: true
    add_mutation_type: true
    # add id field to all schema types
    field_for_id: true
    # add creation date and last update date field(s) to all schema types
    field_for_creation_date: false
    field_for_last_update_date: false
    # add reverse edges for traversal
    reverse_edges: true
    # add edge types
    edge_types: false
    fields_for_edge_types: false
    # add queries
    query_by_id: true
    query_type_filter: true
    query_list_of: true
    query_by_key: true
    # add input types
    input_to_create_objects: true
    input_to_update_objects: true
    # add edge input types (update not supported)
    input_to_create_edge_objects: true
    input_to_update_edge_objects: false
    # add mutations
    create_objects: true
    update_objects: true
    delete_objects: false
    # add edge mutations (update and delete not supported)
    create_edge_objects: true
    update_edge_objects: false
    delete_edge_objects: false
