transform:
    type_names: PascalCase
    field_names: camelCase
    enum_values: uppercase
    drop_comments: true
generation:
    # add id field to all schema types
    field_for_id: true
    # add reverse edges for traversal
    reverse_edges: true
    # add edge types
    edge_types: false
    fields_for_edge_types: false
    # add queries
    query_by_id: true
    query_list_of: true
    # add input types
    input_to_create_objects: true
    input_to_update_objects: true
    # add edge input types (not supported)
    input_to_create_edge_objects: false
    input_to_update_edge_objects: false
    # add mutations
    create_objects: true
    update_objects: true
    delete_objects: true
    # add edge mutations (not supported)
    create_edge_objects: false
    update_edge_objects: false
    delete_edge_objects: false
